### ISSUE TITLE
Crash when pluggin/unplugging/while connected on charger.

### ISSUE THREAD

**Issue by ApostolosB** [sailfishos-sony-tama/main#86]
Has anyone noticed anything like it. Its a rare crash and seems to be happening while plugging or unplugging the charger and the phone tries to wake up to notify you that you plugged/unplugged. Or maybe when it reaches the 100% level and tries to wake up. 

And to be more specific by crash i mean an unresponsive phone that requires a reboot.

**Comment by pagism** [comment]
I have not noticed anything like that on XZ3, usually I charge the device around ~85%, although few times I forgot it and charged up to 100% without any issues. Since 3.3 upgrade, and apart from the camera, the device is very stable, saying that I had few times kuri/laufhelden sports app failing to start, but I think it's an app related issue.

**Comment by rinigus** [comment]
Not here either. But I am usually using wireless charging and it is in a bit different mode then (CPU sleep is inhibited, for example).

**Comment by ApostolosB** [comment]
Hmmmm. Ok. I'll leave this open for a bit more and see if it happens again. If not i'll close it myself. 

Thanks guys. :)

**Comment by Maximilian1st** [comment]
The first crash I had with SFOS since at least a year has happened a few days ago while the XZ2C was charging and an SMS came in and I was speedy enough to touch the notification and the phone just became black with the LED blinking red at which point I had to press power and volume up to restart the phone.

**Comment by ApostolosB** [comment]
I'll close this since we moved to a newer base and open a new one in case i see any crash.
